import { collection, addDoc, Timestamp, GeoPoint } from "firebase/firestore";
import { db } from "../../../packages/firebase/src/config/firebase";
import type { Happening } from "../../../packages/firebase/src/types/happening";

export async function injectPretoriaHappenings() {
  const nowMs = Date.now();
  const hourMs = 60 * 60 * 1000;

  // Fully-typed array ensuring all fields from Happening are populated
  const venues: (Happening & { offsetHours: number })[] = [
    // --- YOUR ORIGINAL 7 EVENTS ---
    {
      id: "evt-usr-001",
      partner_id: 101,
      title: "Garden Social & Artisan Market",
      thumbnail_url: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=800",
      description: "Relaxed morning gathering featuring local craft stalls and fresh coffee in the garden.",
      category: "NATURE",
      offsetHours: 1, // Happening Now
      dateTime: Timestamp.fromDate(new Date(nowMs + 1 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.7981,28.3496",
      locationName: "Mooikrans Venue and Garden, Olympus AH, Pretoria",
      coordinates: new GeoPoint(-25.7981, 28.3496),
      attendees: ["u1", "u2", "u3", "u4", "u5", "u6"],
      rsvps: ["u1", "u2", "u3"],
    },
    {
      id: "evt-usr-002",
      partner_id: 102,
      title: "Wild Café Acoustic Afternoon",
      thumbnail_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800",
      description: "Live local acoustic sets, great food, and drinks under the trees.",
      category: "MUSIC",
      offsetHours: 24, // Upcoming
      dateTime: Timestamp.fromDate(new Date(nowMs + 24 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.7785,28.3188",
      locationName: "The Wild Café, Faerie Glen, Pretoria",
      coordinates: new GeoPoint(-25.7785, 28.3188),
      attendees: ["u1", "u2"],
      rsvps: ["u1"],
    },
    {
      id: "evt-usr-003",
      partner_id: 103,
      title: "Trail Run & Outdoor Fitness",
      thumbnail_url: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?q=80&w=800",
      description: "Morning group trail run through Hedianga Farm followed by coffee.",
      category: "SPORT",
      offsetHours: 48, // Upcoming / Trending
      dateTime: Timestamp.fromDate(new Date(nowMs + 48 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.8033,28.3581",
      locationName: "Hedianga Farm, Olympus AH, Pretoria",
      coordinates: new GeoPoint(-25.8033, 28.3581),
      attendees: ["u1", "u2", "u3", "u4", "u5", "u6", "u7"],
      rsvps: ["u1", "u2", "u4"],
    },
    {
      id: "evt-usr-004",
      partner_id: 104,
      title: "Live Theatre & Musical Tribute",
      thumbnail_url: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?q=80&w=800",
      description: "A high-energy live musical performance featuring hits from the 80s and 90s.",
      category: "MUSIC",
      offsetHours: 2, // Happening Now
      dateTime: Timestamp.fromDate(new Date(nowMs + 2 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.7828,28.2755",
      locationName: "The Barnyard Theatre Menlyn, Menlyn Park Shopping Centre, Pretoria",
      coordinates: new GeoPoint(-25.7828, 28.2755),
      attendees: ["u1", "u2", "u3", "u4", "u5", "u6", "u7", "u8"],
      rsvps: ["u1", "u2", "u3", "u4"],
    },
    {
      id: "evt-usr-005",
      partner_id: 105,
      title: "Friday Night Pool Tournament",
      thumbnail_url: "https://images.unsplash.com/photo-1534158914592-062992fbe900?q=80&w=800",
      description: "Eight-ball pool tournament open to all skill levels. Great prizes up for grabs!",
      category: "GAMES",
      offsetHours: 30, // Upcoming
      dateTime: Timestamp.fromDate(new Date(nowMs + 30 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.8152,28.2933",
      locationName: "The Crucible Billiards Room, Moreletapark, Pretoria",
      coordinates: new GeoPoint(-25.8152, 28.2933),
      attendees: ["u1", "u2", "u3", "u4"],
      rsvps: ["u1", "u2"],
    },
    {
      id: "evt-usr-006",
      partner_id: 106,
      title: "Family Picnic & Kids Fun Day",
      thumbnail_url: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?q=80&w=800",
      description: "Bring a picnic blanket and enjoy outdoor games, play areas, and food stalls.",
      category: "FAMILY",
      offsetHours: 0, // Happening Now
      dateTime: Timestamp.fromDate(new Date(nowMs)),
      google_maps_link: "https://maps.google.com/?q=-25.7886,28.2989",
      locationName: "Zita Park, Garsfontein, Pretoria",
      coordinates: new GeoPoint(-25.7886, 28.2989),
      attendees: ["u1", "u2", "u3", "u4", "u5", "u6"],
      rsvps: ["u1", "u2"],
    },
    {
      id: "evt-usr-007",
      partner_id: 107,
      title: "Bus Stop 7 Open-Air Market",
      thumbnail_url: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?q=80&w=800",
      description: "Fresh produce, artisanal treats, craft beer, and live entertainment for the whole family.",
      category: "FAMILY",
      offsetHours: 52, // Upcoming
      dateTime: Timestamp.fromDate(new Date(nowMs + 52 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.8242,28.3478",
      locationName: "Bus Stop 7 Market, Mooikloof AH, Pretoria",
      coordinates: new GeoPoint(-25.8242, 28.3478),
      attendees: ["u1", "u2", "u3"],
      rsvps: ["u1"],
    },

    // --- 10 ADDITIONAL PRETORIA, CENTURION, MIDRAND & JHB EVENTS ---
    {
      id: "evt-reg-008",
      partner_id: 108,
      title: "Sunset Jazz at Union Buildings",
      thumbnail_url: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=800",
      description: "Relaxing evening of live jazz music on the lawns with food trucks and craft beer.",
      category: "MUSIC",
      offsetHours: 5,
      dateTime: Timestamp.fromDate(new Date(nowMs + 5 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.7402,28.2120",
      locationName: "Union Buildings Lawns, Pretoria Central",
      coordinates: new GeoPoint(-25.7402, 28.2120),
      attendees: ["u1", "u3", "u5"],
      rsvps: ["u1", "u2"],
    },
    {
      id: "evt-reg-009",
      partner_id: 109,
      title: "Hazel Food Market Saturday",
      thumbnail_url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=800",
      description: "Artisanal food market with fresh bakes, international street food, and craft stalls.",
      category: "FOOD",
      offsetHours: 18,
      dateTime: Timestamp.fromDate(new Date(nowMs + 18 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.7725,28.2561",
      locationName: "Greenlyn Village, Menlo Park, Pretoria",
      coordinates: new GeoPoint(-25.7725, 28.2561),
      attendees: ["u2", "u4", "u6", "u7"],
      rsvps: ["u2", "u3"],
    },
    {
      id: "evt-reg-010",
      partner_id: 110,
      title: "Irene Farm Milkshake & Family Day",
      thumbnail_url: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?q=80&w=800",
      description: "A fun family day out meeting dairy cows, enjoying fresh farm treats, and picnics.",
      category: "FAMILY",
      offsetHours: 12,
      dateTime: Timestamp.fromDate(new Date(nowMs + 12 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.8783,28.2239",
      locationName: "Irene Farm, Nelmapius Drive, Centurion",
      coordinates: new GeoPoint(-25.8783, 28.2239),
      attendees: ["u1", "u2", "u5"],
      rsvps: ["u1", "u4"],
    },
    {
      id: "evt-reg-011",
      partner_id: 111,
      title: "SuperSport Park T20 Social Cricket",
      thumbnail_url: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?q=80&w=800",
      description: "Community T20 exhibition match with grass embankment seating and food stalls.",
      category: "SPORT",
      offsetHours: 36,
      dateTime: Timestamp.fromDate(new Date(nowMs + 36 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.8603,28.1952",
      locationName: "SuperSport Park, West Avenue, Centurion",
      coordinates: new GeoPoint(-25.8603, 28.1952),
      attendees: ["u3", "u4", "u8"],
      rsvps: ["u3"],
    },
    {
      id: "evt-reg-012",
      partner_id: 112,
      title: "Rietvlei Dam Rhino Sanctuary Walk",
      thumbnail_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800",
      description: "Guided game drive and birdwatching around the reservoir at Rietvlei Nature Reserve.",
      category: "NATURE",
      offsetHours: 8,
      dateTime: Timestamp.fromDate(new Date(nowMs + 8 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-25.8821,28.2815",
      locationName: "Rietvlei Nature Reserve, Game Reserve Ave, Centurion",
      coordinates: new GeoPoint(-25.8821, 28.2815),
      attendees: ["u1", "u6"],
      rsvps: ["u1"],
    },
    {
      id: "evt-reg-013",
      partner_id: 113,
      title: "Mall of Africa Tech & Gaming Expo",
      thumbnail_url: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?q=80&w=800",
      description: "Hands-on gaming tournaments, VR demos, and cosplay competitions.",
      category: "GAMES",
      offsetHours: 20,
      dateTime: Timestamp.fromDate(new Date(nowMs + 20 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-26.0153,28.1072",
      locationName: "Mall of Africa, Magwa Crescent, Midrand",
      coordinates: new GeoPoint(-26.0153, 28.1072),
      attendees: ["u1", "u2", "u3", "u4", "u9"],
      rsvps: ["u1", "u2"],
    },
    {
      id: "evt-reg-014",
      partner_id: 114,
      title: "Montecasino Piazza Movie Night",
      thumbnail_url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=800",
      description: "Open-air cinema screening on the outdoor piazza with beanbags and drinks.",
      category: "FAMILY",
      offsetHours: 14,
      dateTime: Timestamp.fromDate(new Date(nowMs + 14 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-26.0244,28.0128",
      locationName: "Montecasino Piazza, Fourways, Johannesburg",
      coordinates: new GeoPoint(-26.0244, 28.0128),
      attendees: ["u4", "u5", "u6"],
      rsvps: ["u4"],
    },
    {
      id: "evt-reg-015",
      partner_id: 115,
      title: "Sandton City Rooftop Sunset Cocktails",
      thumbnail_url: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=800",
      description: "DJ sets, craft cocktails, and skyline views across Sandton.",
      category: "MUSIC",
      offsetHours: 28,
      dateTime: Timestamp.fromDate(new Date(nowMs + 28 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-26.1076,28.0527",
      locationName: "Sandton City Rooftop, 83 Rivonia Rd, Sandton",
      coordinates: new GeoPoint(-26.1076, 28.0527),
      attendees: ["u2", "u3", "u7"],
      rsvps: ["u2"],
    },
    {
      id: "evt-reg-016",
      partner_id: 116,
      title: "Rosebank Rooftop Sunday Market",
      thumbnail_url: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?q=80&w=800",
      description: "Rooftop market with vintage clothing, artisan food stalls, and acoustic music.",
      category: "FOOD",
      offsetHours: 40,
      dateTime: Timestamp.fromDate(new Date(nowMs + 40 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-26.1458,28.0436",
      locationName: "Rosebank Mall Rooftop, 50 Bath Ave, Rosebank, Johannesburg",
      coordinates: new GeoPoint(-26.1458, 28.0436),
      attendees: ["u1", "u5", "u8"],
      rsvps: ["u1", "u5"],
    },
    {
      id: "evt-reg-017",
      partner_id: 117,
      title: "Emmarentia Dam Kayak & Picnic",
      thumbnail_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800",
      description: "Social canoeing session on the dam followed by a picnic in the Botanic Gardens.",
      category: "NATURE",
      offsetHours: 60,
      dateTime: Timestamp.fromDate(new Date(nowMs + 60 * hourMs)),
      google_maps_link: "https://maps.google.com/?q=-26.1558,28.0053",
      locationName: "Emmarentia Dam, Olifants Rd, Emmarentia, Johannesburg",
      coordinates: new GeoPoint(-26.1558, 28.0053),
      attendees: ["u3", "u6"],
      rsvps: ["u3"],
    },
  ];

  for (const item of venues) {
    const eventDate = new Date(nowMs + item.offsetHours * hourMs);
    await addDoc(collection(db, "happenings"), {
      partner_id: item.partner_id,
      title: item.title,
      thumbnail_url: item.thumbnail_url,
      description: item.description,
      dateTime: Timestamp.fromDate(eventDate),
      google_maps_link: item.google_maps_link,
      locationName: item.locationName,
      coordinates: item.coordinates,
      rsvps: item.rsvps,
      attendees: item.attendees,
      category: item.category,
      createdAt: Timestamp.now(),
    });
  }

  console.log("Successfully seeded 17 Happenings adhering strictly to the model schema!");
}